NOla @user.name@, aqui na nossa linda BBS  @system.name@ (@system.inet_addr@)
as contas sao automaticamente deletadas apos  @system.autodel@ dias sem uso
e sua conta sera fechada e marcada para exclusao.
Situacao chata, nao eh mesmo?

Entao aproveite esta oportunidade e logue novamente, para evitar aborrecimentos
e manter sua conta ativa. Afinal, nosso sistema esta no ar por voce! :)

Valeu pela sua presenca aqui e te vemos na BBS,

@system.operator@
Z